kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: httpd
    weight: 100
  wildcardPolicy: None